import os
import nbformat as nbf

def create_ercot_notebook():
    nb = nbf.v4.new_notebook()
    nb.metadata = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    }
    
    # Cells list
    cells = []
    
    # Cell 1: Intro
    cells.append(nbf.v4.new_markdown_cell(
        "# XGBoost Probabilistic Forecasting with Daily Rolling Retraining (ERCOT Dallas)\n\n"
        "This notebook implements the rolling retraining benchmark for ERCOT Dallas. "
        "Unlike the static benchmark, we retrain the XGBoost models at the start of each forecast day "
        "using a sliding 2-year historical window. This avoids model outdatedness and ensures "
        "absolute comparability against zero-shot foundation models (like Chronos-2) which are "
        "always given the immediate past context."
    ))
    
    # Cell 2: Imports
    cells.append(nbf.v4.new_code_cell(
        "import pandas as pd\n"
        "import numpy as np\n"
        "import glob\n"
        "import xgboost as xgb\n"
        "import holidays\n"
        "from sklearn.metrics import mean_absolute_error, mean_squared_error\n"
        "import matplotlib.pyplot as plt\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n\n"
        "HORIZON = 24"
    ))
    
    # Cell 3: Data Loading
    cells.append(nbf.v4.new_code_cell(
        "def load_ercot_data():\n"
        "    files = sorted(glob.glob('../../data/ercot/raw/ercot_20*.xlsx'))\n"
        "    dfs = []\n"
        "    for f in files:\n"
        "        df = pd.read_excel(f)\n"
        "        dfs.append(df)\n"
        "    df = pd.concat(dfs, ignore_index=True)\n"
        "    \n"
        "    def parse_ercot_datetime(s):\n"
        "        s = str(s).replace(' DST', '')\n"
        "        if s.endswith('24:00'):\n"
        "            return pd.to_datetime(s.replace('24:00', '00:00')) + pd.Timedelta(days=1) - pd.Timedelta(hours=1)\n"
        "        else:\n"
        "            return pd.to_datetime(s) - pd.Timedelta(hours=1)\n\n"
        "    df['timestamp'] = df['Hour Ending'].apply(parse_ercot_datetime)\n"
        "    df = df[['timestamp', 'NCENT']].copy()\n"
        "    df.rename(columns={'NCENT': 'target'}, inplace=True)\n"
        "    df = df.sort_values('timestamp').set_index('timestamp')\n"
        "    df = df.resample('h').mean()\n"
        "    df['target'] = df['target'].interpolate()\n"
        "    return df\n\n"
        "def load_weather_data():\n"
        "    files = sorted(glob.glob('../../data/ercot/raw/open-meteo-dallas-*.csv'))\n"
        "    dfs = []\n"
        "    for f in files:\n"
        "        df_w = pd.read_csv(f, skiprows=3)\n"
        "        dfs.append(df_w)\n"
        "    df_w = pd.concat(dfs, ignore_index=True)\n"
        "    \n"
        "    df_w['timestamp'] = pd.to_datetime(df_w['time'])\n"
        "    df_w = df_w.rename(columns={\n"
        "        'temperature_2m (°C)': 'temp',\n"
        "        'relative_humidity_2m (%)': 'humidity',\n"
        "        'dew_point_2m (°C)': 'dew_point',\n"
        "        'apparent_temperature (°C)': 'apparent_temp',\n"
        "        'wind_speed_10m (km/h)': 'wind_speed',\n"
        "        'cloud_cover (%)': 'cloud_cover',\n"
        "        'precipitation (mm)': 'precip',\n"
        "        'shortwave_radiation (W/m²)': 'radiation'\n"
        "    })\n"
        "    \n"
        "    cols = ['timestamp', 'temp', 'humidity', 'dew_point', 'apparent_temp', 'wind_speed', 'cloud_cover', 'precip', 'radiation']\n"
        "    df_w = df_w[cols].set_index('timestamp')\n"
        "    df_w = df_w.resample('h').mean().interpolate()\n"
        "    return df_w\n\n"
        "df_load = load_ercot_data()\n"
        "df_weather = load_weather_data()\n"
        "df = df_load.join(df_weather, how='inner')\n"
        "print(f\"Merged data from {df.index.min()} to {df.index.max()}\")\n\n"
        "# Pre-compute rolling features on target load\n"
        "for w in [6, 12, 24]:\n"
        "    df[f'load_roll_mean_{w}h'] = df['target'].rolling(window=w).mean()\n"
        "    df[f'load_roll_min_{w}h'] = df['target'].rolling(window=w).min()\n"
        "    df[f'load_roll_max_{w}h'] = df['target'].rolling(window=w).max()\n"
        "    df[f'load_roll_std_{w}h'] = df['target'].rolling(window=w).std()\n\n"
        "# Pre-compute rolling features on weather variables\n"
        "for w in [3, 6, 12, 48, 72]:\n"
        "    df[f'temp_roll_mean_{w}h'] = df['temp'].rolling(window=w).mean()\n"
        "    df[f'apparent_temp_roll_mean_{w}h'] = df['apparent_temp'].rolling(window=w).mean()\n"
        "    df[f'radiation_roll_mean_{w}h'] = df['radiation'].rolling(window=w).mean()\n\n"
        "# Degree days and weather interactions\n"
        "df['cdd'] = (df['temp'] - 18.33).clip(lower=0)\n"
        "df['hdd'] = (18.33 - df['temp']).clip(lower=0)\n"
        "df['apparent_cdd'] = (df['apparent_temp'] - 18.33).clip(lower=0)\n"
        "df['temp_humidity_interaction'] = df['temp'] * df['humidity']"
    ))
    
    # Cell 4: Feature Engineering
    cells.append(nbf.v4.new_code_cell(
        "tx_holidays = holidays.US(state='TX')\n\n"
        "def get_calendar_features(dt_index):\n"
        "    features = pd.DataFrame(index=dt_index)\n"
        "    features['hour'] = dt_index.hour\n"
        "    features['dayofweek'] = dt_index.dayofweek\n"
        "    features['is_weekend'] = (dt_index.dayofweek >= 5).astype(int)\n"
        "    features['month'] = dt_index.month\n"
        "    features['is_holiday'] = pd.Series(dt_index).apply(lambda x: x in tx_holidays).values.astype(int)\n"
        "    return features"
    ))
    
    # Cell 5: Daily Rolling Training and Prediction Loop
    cells.append(nbf.v4.new_code_cell(
        "# Feature configurations\n"
        "lag_cols = ['feat_origin', 'feat_origin_m1', 'feat_origin_m2', \n"
        "            'feat_24h_aligned', 'feat_48h_aligned', 'feat_168h_aligned']\n\n"
        "roll_load_cols = []\n"
        "for w in [6, 12, 24]:\n"
        "    roll_load_cols.extend([f'load_roll_mean_{w}h', f'load_roll_min_{w}h', \n"
        "                           f'load_roll_max_{w}h', f'load_roll_std_{w}h'])\n\n"
        "cal_cols = ['target_hour', 'target_dayofweek', 'target_is_weekend', 'target_month', 'target_is_holiday']\n\n"
        "weather_cols = ['target_temp', 'target_humidity', 'target_dew_point', 'target_apparent_temp', \n"
        "                'target_wind_speed', 'target_cloud_cover', 'target_precip', 'target_radiation']\n\n"
        "degree_cols = ['target_cdd', 'target_hdd', 'target_apparent_cdd']\n\n"
        "roll_weather_cols = []\n"
        "for w in [3, 6, 12, 48, 72]:\n"
        "    roll_weather_cols.extend([f'target_temp_roll_mean_{w}h', \n"
        "                              f'target_apparent_temp_roll_mean_{w}h', \n"
        "                              f'target_radiation_roll_mean_{w}h'])\n\n"
        "interaction_cols = ['target_temp_humidity_interaction', 'target_temp_hour_interaction']\n\n"
        "feature_cols = lag_cols + roll_load_cols + cal_cols + weather_cols + degree_cols + roll_weather_cols + interaction_cols\n\n"
        "# Pre-build df_h dataframes for each horizon\n"
        "df_h_dict = {}\n"
        "for h in range(1, HORIZON + 1):\n"
        "    df_h = df.copy()\n"
        "    \n"
        "    df_h['feat_origin'] = df_h['target']\n"
        "    df_h['feat_origin_m1'] = df_h['target'].shift(1)\n"
        "    df_h['feat_origin_m2'] = df_h['target'].shift(2)\n"
        "    df_h['feat_24h_aligned'] = df_h['target'].shift(24 - h)\n"
        "    df_h['feat_48h_aligned'] = df_h['target'].shift(48 - h)\n"
        "    df_h['feat_168h_aligned'] = df_h['target'].shift(168 - h)\n"
        "    \n"
        "    df_h['target_h'] = df_h['target'].shift(-h)\n"
        "    df_h['residual_target_h'] = df_h['target_h'] - df_h['feat_24h_aligned']\n"
        "    \n"
        "    target_times = df_h.index + pd.Timedelta(hours=h)\n"
        "    cal_feats = get_calendar_features(target_times)\n"
        "    df_h['target_hour'] = cal_feats['hour'].values\n"
        "    df_h['target_dayofweek'] = cal_feats['dayofweek'].values\n"
        "    df_h['target_is_weekend'] = cal_feats['is_weekend'].values\n"
        "    df_h['target_month'] = cal_feats['month'].values\n"
        "    df_h['target_is_holiday'] = cal_feats['is_holiday'].values\n"
        "    \n"
        "    df_h['target_temp'] = df_h['temp'].shift(-h)\n"
        "    df_h['target_humidity'] = df_h['humidity'].shift(-h)\n"
        "    df_h['target_dew_point'] = df_h['dew_point'].shift(-h)\n"
        "    df_h['target_apparent_temp'] = df_h['apparent_temp'].shift(-h)\n"
        "    df_h['target_wind_speed'] = df_h['wind_speed'].shift(-h)\n"
        "    df_h['target_cloud_cover'] = df_h['cloud_cover'].shift(-h)\n"
        "    df_h['target_precip'] = df_h['precip'].shift(-h)\n"
        "    df_h['target_radiation'] = df_h['radiation'].shift(-h)\n"
        "    \n"
        "    df_h['target_cdd'] = df_h['cdd'].shift(-h)\n"
        "    df_h['target_hdd'] = df_h['hdd'].shift(-h)\n"
        "    df_h['target_apparent_cdd'] = df_h['apparent_cdd'].shift(-h)\n"
        "    \n"
        "    for w in [3, 6, 12, 48, 72]:\n"
        "        df_h[f'target_temp_roll_mean_{w}h'] = df_h[f'temp_roll_mean_{w}h'].shift(-h)\n"
        "        df_h[f'target_apparent_temp_roll_mean_{w}h'] = df_h[f'apparent_temp_roll_mean_{w}h'].shift(-h)\n"
        "        df_h[f'target_radiation_roll_mean_{w}h'] = df_h[f'radiation_roll_mean_{w}h'].shift(-h)\n"
        "        \n"
        "    df_h['target_temp_humidity_interaction'] = df_h['temp_humidity_interaction'].shift(-h)\n"
        "    df_h['target_temp_hour_interaction'] = df_h['target_temp'] * df_h['target_hour']\n"
        "    \n"
        "    df_h = df_h.dropna()\n"
        "    df_h_dict[h] = df_h"
    ))
    
    # Cell 6: Rolling Evaluator Function
    cells.append(nbf.v4.new_code_cell(
        "def evaluate_rolling_xgboost(test_df, df_h_dict):\n"
        "    all_preds = []\n"
        "    all_actuals = []\n"
        "    all_lowers = []\n"
        "    all_uppers = []\n"
        "    origins = test_df[test_df.index.hour == 0].index\n"
        "    for day_idx, origin in enumerate(origins):\n"
        "        if origin + pd.Timedelta(hours=24) > test_df.index[-1]:\n"
        "            continue\n"
        "        actual = test_df.loc[origin + pd.Timedelta(hours=1) : origin + pd.Timedelta(hours=24), 'target'].values\n"
        "        \n"
        "        # Train sliding window 2 years before origin\n"
        "        train_start = origin - pd.DateOffset(years=2)\n"
        "        \n"
        "        preds = []\n"
        "        lowers = []\n"
        "        uppers = []\n"
        "        for h in range(1, 25):\n"
        "            df_h = df_h_dict[h]\n"
        "            # Target T'+h is only known if target timestamp <= origin T\n"
        "            train_end = origin - pd.Timedelta(hours=h)\n"
        "            train_h = df_h.loc[train_start:train_end]\n"
        "            \n"
        "            val_size = int(len(train_h) * 0.15)\n"
        "            train_split = train_h.iloc[:-val_size]\n"
        "            val_split = train_h.iloc[-val_size:]\n"
        "            \n"
        "            # Fit Point Model\n"
        "            m_point = xgb.XGBRegressor(\n"
        "                n_estimators=1000,\n"
        "                learning_rate=0.03,\n"
        "                max_depth=5,\n"
        "                subsample=0.8,\n"
        "                colsample_bytree=0.6,\n"
        "                reg_lambda=3.0,\n"
        "                reg_alpha=0.5,\n"
        "                early_stopping_rounds=30,\n"
        "                random_state=42,\n"
        "                n_jobs=-1\n"
        "            )\n"
        "            m_point.fit(\n"
        "                train_split[feature_cols].astype(float), \n"
        "                train_split['residual_target_h'],\n"
        "                eval_set=[(val_split[feature_cols].astype(float), val_split['residual_target_h'])],\n"
        "                verbose=False\n"
        "            )\n"
        "            \n"
        "            # Fit Quantile Model\n"
        "            m_quant = xgb.XGBRegressor(\n"
        "                objective='reg:quantileerror',\n"
        "                quantile_alpha=[0.05, 0.95],\n"
        "                n_estimators=1000,\n"
        "                learning_rate=0.03,\n"
        "                max_depth=5,\n"
        "                subsample=0.8,\n"
        "                colsample_bytree=0.6,\n"
        "                reg_lambda=3.0,\n"
        "                reg_alpha=0.5,\n"
        "                early_stopping_rounds=30,\n"
        "                random_state=42,\n"
        "                n_jobs=-1\n"
        "            )\n"
        "            m_quant.fit(\n"
        "                train_split[feature_cols].astype(float), \n"
        "                train_split['residual_target_h'],\n"
        "                eval_set=[(val_split[feature_cols].astype(float), val_split['residual_target_h'])],\n"
        "                verbose=False\n"
        "            )\n"
        "            \n"
        "            # Predict for origin\n"
        "            feats = df_h.loc[[origin]]\n"
        "            feat_24h_aligned = feats['feat_24h_aligned'].values[0]\n"
        "            \n"
        "            pred_residual = m_point.predict(feats[feature_cols].astype(float))[0]\n"
        "            pred_raw = pred_residual + feat_24h_aligned\n"
        "            preds.append(pred_raw)\n"
        "            \n"
        "            quantiles_residual = m_quant.predict(feats[feature_cols].astype(float))[0]\n"
        "            lower_raw = quantiles_residual[0] + feat_24h_aligned\n"
        "            upper_raw = quantiles_residual[1] + feat_24h_aligned\n"
        "            lowers.append(lower_raw)\n"
        "            uppers.append(upper_raw)\n\n"
        "        all_preds.append(preds)\n"
        "        all_actuals.append(actual)\n"
        "        all_lowers.append(lowers)\n"
        "        all_uppers.append(uppers)\n"
        "        if (day_idx + 1) % 5 == 0 or (day_idx + 1) == len(origins):\n"
        "            print(f\"Processed day {day_idx + 1}/{len(origins)}\")\n"
        "    return np.array(all_actuals), np.array(all_preds), np.array(all_lowers), np.array(all_uppers)"
    ))
    
    # Cell 7: Metrics compilation and run
    cells.append(nbf.v4.new_code_cell(
        "def calculate_metrics(y_true, y_pred, y_train, y_lower=None, y_upper=None):\n"
        "    mae = mean_absolute_error(y_true, y_pred)\n"
        "    rmse = np.sqrt(mean_squared_error(y_true, y_pred))\n"
        "    smape = 100 * np.mean(2 * np.abs(y_pred - y_true) / (np.abs(y_pred) + np.abs(y_true)))\n"
        "    mae_naive = mean_absolute_error(y_train[168:], y_train[:-168])\n"
        "    mase = mae / mae_naive\n"
        "    \n"
        "    metrics = {'MAE': mae, 'RMSE': rmse, 'sMAPE': smape, 'MASE': mase}\n"
        "    if y_lower is not None and y_upper is not None:\n"
        "        inside = (y_true >= y_lower) & (y_true <= y_upper)\n"
        "        metrics['Coverage'] = 100 * np.mean(inside)\n"
        "    return metrics\n\n"
        "aug_df = df['2025-08-01 00:00:00':'2025-08-31 23:00:00']\n"
        "mar_df = df['2026-03-01 00:00:00':'2026-03-31 23:00:00']\n\n"
        "results = {}\n"
        "for window_name, test_df in [(\"August 2025\", aug_df), (\"March 2026\", mar_df)]:\n"
        "    print(f\"\\nEvaluating {window_name}...\")\n"
        "    act, p_dir, p_lower, p_upper = evaluate_rolling_xgboost(test_df, df_h_dict)\n"
        "    results[window_name] = (act, p_dir, p_lower, p_upper)\n"
        "    # train_df target variable used for naive calculation baseline\n"
        "    train_df = df[:test_df.index[0] - pd.Timedelta(hours=1)]\n"
        "    metrics = calculate_metrics(act.flatten(), p_dir.flatten(), train_df['target'], p_lower.flatten(), p_upper.flatten())\n"
        "    print(f\"\\nResults for {window_name} (XGBoost Rolling Retraining):\")\n"
        "    print(metrics)"
    ))
    
    # Cell 8: Plotting sample day
    cells.append(nbf.v4.new_code_cell(
        "sample_origin = '2026-03-15 00:00:00'\n"
        "origin_ts = pd.Timestamp(sample_origin)\n"
        "origins = mar_df[mar_df.index.hour == 0].index\n"
        "sample_idx = list(origins).index(origin_ts)\n\n"
        "act_sample = results['March 2026'][0][sample_idx]\n"
        "wea_preds = results['March 2026'][1][sample_idx]\n"
        "wea_lowers = results['March 2026'][2][sample_idx]\n"
        "wea_uppers = results['March 2026'][3][sample_idx]\n\n"
        "plt.figure(figsize=(12, 6))\n"
        "plt.plot(range(1, 25), act_sample, label='Actual', marker='o', color='black')\n"
        "plt.plot(range(1, 25), wea_preds, label='XGBoost Point Prediction', linestyle='--', color='red')\n"
        "plt.fill_between(range(1, 25), wea_lowers, wea_uppers, color='red', alpha=0.15, label='XGBoost 90% Prediction Interval')\n"
        "plt.title(f\"Probabilistic XGBoost Forecast with Rolling Train - Origin: {sample_origin}\")\n"
        "plt.xlabel('Horizon (Hours)')\n"
        "plt.ylabel('Energy Demand (NCENT)')\n"
        "plt.legend()\n"
        "plt.grid(True)\n"
        "plt.show()"
    ))
    
    nb['cells'] = cells
    
    os.makedirs('notebooks/xgboost-rolling', exist_ok=True)
    with open('notebooks/xgboost-rolling/ercot-xgboost-rolling.ipynb', 'w') as f:
        nbf.write(nb, f)
    print("Created notebooks/xgboost-rolling/ercot-xgboost-rolling.ipynb")

def create_ieso_notebook():
    nb = nbf.v4.new_notebook()
    nb.metadata = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    }
    
    # Cells list
    cells = []
    
    # Cell 1: Intro
    cells.append(nbf.v4.new_markdown_cell(
        "# XGBoost Probabilistic Forecasting with Daily Rolling Retraining (IESO Toronto)\n\n"
        "This notebook implements the rolling retraining benchmark for IESO Toronto. "
        "Unlike the static benchmark, we retrain the XGBoost models at the start of each forecast day "
        "using a sliding 2-year historical window. This avoids model outdatedness and ensures "
        "absolute comparability against zero-shot foundation models (like Chronos-2) which are "
        "always given the immediate past context."
    ))
    
    # Cell 2: Imports
    cells.append(nbf.v4.new_code_cell(
        "import pandas as pd\n"
        "import numpy as np\n"
        "import xgboost as xgb\n"
        "import holidays\n"
        "from sklearn.metrics import mean_absolute_error, mean_squared_error\n"
        "import matplotlib.pyplot as plt\n"
        "import warnings\n"
        "warnings.filterwarnings('ignore')\n\n"
        "HORIZON = 24"
    ))
    
    # Cell 3: Data Loading
    cells.append(nbf.v4.new_code_cell(
        "data_path = '../../data/ieso/ieso_toronto_covariate_2023_2025.csv'\n"
        "df = pd.read_csv(data_path)\n"
        "df['timestamp'] = pd.to_datetime(df['timestamp'])\n"
        "df = df.set_index('timestamp')\n"
        "print(f\"Loaded covariate data from {df.index.min()} to {df.index.max()}\")\n\n"
        "# Pre-compute rolling features on target energy\n"
        "for w in [6, 12, 24]:\n"
        "    df[f'load_roll_mean_{w}h'] = df['energy'].rolling(window=w).mean()\n"
        "    df[f'load_roll_min_{w}h'] = df['energy'].rolling(window=w).min()\n"
        "    df[f'load_roll_max_{w}h'] = df['energy'].rolling(window=w).max()\n"
        "    df[f'load_roll_std_{w}h'] = df['energy'].rolling(window=w).std()\n\n"
        "# Pre-compute rolling features on weather variables\n"
        "for w in [3, 6, 12, 48, 72]:\n"
        "    df[f'temp_roll_mean_{w}h'] = df['temp'].rolling(window=w).mean()\n"
        "    df[f'apparent_temp_roll_mean_{w}h'] = df['apparent_temp'].rolling(window=w).mean()\n"
        "    df[f'radiation_roll_mean_{w}h'] = df['radiation'].rolling(window=w).mean()\n\n"
        "# Degree days and weather interactions\n"
        "df['cdd'] = (df['temp'] - 18.33).clip(lower=0)\n"
        "df['hdd'] = (18.33 - df['temp']).clip(lower=0)\n"
        "df['apparent_cdd'] = (df['apparent_temp'] - 18.33).clip(lower=0)\n"
        "df['temp_humidity_interaction'] = df['temp'] * df['humidity']"
    ))
    
    # Cell 4: Feature Engineering
    cells.append(nbf.v4.new_code_cell(
        "on_holidays = holidays.CA(prov='ON')\n\n"
        "def get_calendar_features(dt_index):\n"
        "    features = pd.DataFrame(index=dt_index)\n"
        "    features['hour'] = dt_index.hour\n"
        "    features['dayofweek'] = dt_index.dayofweek\n"
        "    features['is_weekend'] = (dt_index.dayofweek >= 5).astype(int)\n"
        "    features['month'] = dt_index.month\n"
        "    features['is_holiday'] = pd.Series(dt_index).apply(lambda x: x in on_holidays).values.astype(int)\n"
        "    return features"
    ))
    
    # Cell 5: Daily Rolling Training and Prediction Loop
    cells.append(nbf.v4.new_code_cell(
        "# Feature configurations\n"
        "lag_cols = ['feat_origin', 'feat_origin_m1', 'feat_origin_m2', \n"
        "            'feat_24h_aligned', 'feat_48h_aligned', 'feat_168h_aligned']\n\n"
        "roll_load_cols = []\n"
        "for w in [6, 12, 24]:\n"
        "    roll_load_cols.extend([f'load_roll_mean_{w}h', f'load_roll_min_{w}h', \n"
        "                           f'load_roll_max_{w}h', f'load_roll_std_{w}h'])\n\n"
        "cal_cols = ['target_hour', 'target_dayofweek', 'target_is_weekend', 'target_month', 'target_is_holiday']\n\n"
        "weather_cols = ['target_temp', 'target_humidity', 'target_dew_point', 'target_apparent_temp', \n"
        "                'target_wind_speed', 'target_cloud_cover', 'target_precip', 'target_radiation']\n\n"
        "degree_cols = ['target_cdd', 'target_hdd', 'target_apparent_cdd']\n\n"
        "roll_weather_cols = []\n"
        "for w in [3, 6, 12, 48, 72]:\n"
        "    roll_weather_cols.extend([f'target_temp_roll_mean_{w}h', \n"
        "                              f'target_apparent_temp_roll_mean_{w}h', \n"
        "                              f'target_radiation_roll_mean_{w}h'])\n\n"
        "interaction_cols = ['target_temp_humidity_interaction', 'target_temp_hour_interaction']\n\n"
        "feature_cols = lag_cols + roll_load_cols + cal_cols + weather_cols + degree_cols + roll_weather_cols + interaction_cols\n\n"
        "# Pre-build df_h dataframes for each horizon\n"
        "df_h_dict = {}\n"
        "for h in range(1, HORIZON + 1):\n"
        "    df_h = df.copy()\n"
        "    \n"
        "    df_h['feat_origin'] = df_h['energy']\n"
        "    df_h['feat_origin_m1'] = df_h['energy'].shift(1)\n"
        "    df_h['feat_origin_m2'] = df_h['energy'].shift(2)\n"
        "    df_h['feat_24h_aligned'] = df_h['energy'].shift(24 - h)\n"
        "    df_h['feat_48h_aligned'] = df_h['energy'].shift(48 - h)\n"
        "    df_h['feat_168h_aligned'] = df_h['energy'].shift(168 - h)\n"
        "    \n"
        "    df_h['target_h'] = df_h['energy'].shift(-h)\n"
        "    df_h['residual_target_h'] = df_h['target_h'] - df_h['feat_24h_aligned']\n"
        "    \n"
        "    target_times = df_h.index + pd.Timedelta(hours=h)\n"
        "    cal_feats = get_calendar_features(target_times)\n"
        "    df_h['target_hour'] = cal_feats['hour'].values\n"
        "    df_h['target_dayofweek'] = cal_feats['dayofweek'].values\n"
        "    df_h['target_is_weekend'] = cal_feats['is_weekend'].values\n"
        "    df_h['target_month'] = cal_feats['month'].values\n"
        "    df_h['target_is_holiday'] = cal_feats['is_holiday'].values\n"
        "    \n"
        "    df_h['target_temp'] = df_h['temp'].shift(-h)\n"
        "    df_h['target_humidity'] = df_h['humidity'].shift(-h)\n"
        "    df_h['target_dew_point'] = df_h['dew_point'].shift(-h)\n"
        "    df_h['target_apparent_temp'] = df_h['apparent_temp'].shift(-h)\n"
        "    df_h['target_wind_speed'] = df_h['wind_speed'].shift(-h)\n"
        "    df_h['target_cloud_cover'] = df_h['cloud_cover'].shift(-h)\n"
        "    df_h['target_precip'] = df_h['precip'].shift(-h)\n"
        "    df_h['target_radiation'] = df_h['radiation'].shift(-h)\n"
        "    \n"
        "    df_h['target_cdd'] = df_h['cdd'].shift(-h)\n"
        "    df_h['target_hdd'] = df_h['hdd'].shift(-h)\n"
        "    df_h['target_apparent_cdd'] = df_h['apparent_cdd'].shift(-h)\n"
        "    \n"
        "    for w in [3, 6, 12, 48, 72]:\n"
        "        df_h[f'target_temp_roll_mean_{w}h'] = df_h[f'temp_roll_mean_{w}h'].shift(-h)\n"
        "        df_h[f'target_apparent_temp_roll_mean_{w}h'] = df_h[f'apparent_temp_roll_mean_{w}h'].shift(-h)\n"
        "        df_h[f'target_radiation_roll_mean_{w}h'] = df_h[f'radiation_roll_mean_{w}h'].shift(-h)\n"
        "        \n"
        "    df_h['target_temp_humidity_interaction'] = df_h['temp_humidity_interaction'].shift(-h)\n"
        "    df_h['target_temp_hour_interaction'] = df_h['target_temp'] * df_h['target_hour']\n"
        "    \n"
        "    df_h = df_h.dropna()\n"
        "    df_h_dict[h] = df_h"
    ))
    
    # Cell 6: Rolling Evaluator Function
    cells.append(nbf.v4.new_code_cell(
        "def evaluate_rolling_xgboost(test_df, df_h_dict):\n"
        "    all_preds = []\n"
        "    all_actuals = []\n"
        "    all_lowers = []\n"
        "    all_uppers = []\n"
        "    origins = test_df[test_df.index.hour == 0].index\n"
        "    for day_idx, origin in enumerate(origins):\n"
        "        if origin + pd.Timedelta(hours=24) > test_df.index[-1]:\n"
        "            continue\n"
        "        actual = test_df.loc[origin + pd.Timedelta(hours=1) : origin + pd.Timedelta(hours=24), 'energy'].values\n"
        "        \n"
        "        # Train sliding window 2 years before origin\n"
        "        train_start = origin - pd.DateOffset(years=2)\n"
        "        \n"
        "        preds = []\n"
        "        lowers = []\n"
        "        uppers = []\n"
        "        for h in range(1, 25):\n"
        "            df_h = df_h_dict[h]\n"
        "            # Target T'+h is only known if target timestamp <= origin T\n"
        "            train_end = origin - pd.Timedelta(hours=h)\n"
        "            train_h = df_h.loc[train_start:train_end]\n"
        "            \n"
        "            val_size = int(len(train_h) * 0.15)\n"
        "            train_split = train_h.iloc[:-val_size]\n"
        "            val_split = train_h.iloc[-val_size:]\n"
        "            \n"
        "            # Fit Point Model\n"
        "            m_point = xgb.XGBRegressor(\n"
        "                n_estimators=1000,\n"
        "                learning_rate=0.03,\n"
        "                max_depth=5,\n"
        "                subsample=0.8,\n"
        "                colsample_bytree=0.6,\n"
        "                reg_lambda=3.0,\n"
        "                reg_alpha=0.5,\n"
        "                early_stopping_rounds=30,\n"
        "                random_state=42,\n"
        "                n_jobs=-1\n"
        "            )\n"
        "            m_point.fit(\n"
        "                train_split[feature_cols].astype(float), \n"
        "                train_split['residual_target_h'],\n"
        "                eval_set=[(val_split[feature_cols].astype(float), val_split['residual_target_h'])],\n"
        "                verbose=False\n"
        "            )\n"
        "            \n"
        "            # Fit Quantile Model\n"
        "            m_quant = xgb.XGBRegressor(\n"
        "                objective='reg:quantileerror',\n"
        "                quantile_alpha=[0.05, 0.95],\n"
        "                n_estimators=1000,\n"
        "                learning_rate=0.03,\n"
        "                max_depth=5,\n"
        "                subsample=0.8,\n"
        "                colsample_bytree=0.6,\n"
        "                reg_lambda=3.0,\n"
        "                reg_alpha=0.5,\n"
        "                early_stopping_rounds=30,\n"
        "                random_state=42,\n"
        "                n_jobs=-1\n"
        "            )\n"
        "            m_quant.fit(\n"
        "                train_split[feature_cols].astype(float), \n"
        "                train_split['residual_target_h'],\n"
        "                eval_set=[(val_split[feature_cols].astype(float), val_split['residual_target_h'])],\n"
        "                verbose=False\n"
        "            )\n"
        "            \n"
        "            # Predict for origin\n"
        "            feats = df_h.loc[[origin]]\n"
        "            feat_24h_aligned = feats['feat_24h_aligned'].values[0]\n"
        "            \n"
        "            pred_residual = m_point.predict(feats[feature_cols].astype(float))[0]\n"
        "            pred_raw = pred_residual + feat_24h_aligned\n"
        "            preds.append(pred_raw)\n"
        "            \n"
        "            quantiles_residual = m_quant.predict(feats[feature_cols].astype(float))[0]\n"
        "            lower_raw = quantiles_residual[0] + feat_24h_aligned\n"
        "            upper_raw = quantiles_residual[1] + feat_24h_aligned\n"
        "            lowers.append(lower_raw)\n"
        "            uppers.append(upper_raw)\n\n"
        "        all_preds.append(preds)\n"
        "        all_actuals.append(actual)\n"
        "        all_lowers.append(lowers)\n"
        "        all_uppers.append(uppers)\n"
        "        if (day_idx + 1) % 5 == 0 or (day_idx + 1) == len(origins):\n"
        "            print(f\"Processed day {day_idx + 1}/{len(origins)}\")\n"
        "    return np.array(all_actuals), np.array(all_preds), np.array(all_lowers), np.array(all_uppers)"
    ))
    
    # Cell 7: Metrics compilation and run
    cells.append(nbf.v4.new_code_cell(
        "def calculate_metrics(y_true, y_pred, y_train, y_lower=None, y_upper=None):\n"
        "    mae = mean_absolute_error(y_true, y_pred)\n"
        "    rmse = np.sqrt(mean_squared_error(y_true, y_pred))\n"
        "    smape = 100 * np.mean(2 * np.abs(y_pred - y_true) / (np.abs(y_pred) + np.abs(y_true)))\n"
        "    mae_naive = mean_absolute_error(y_train[168:], y_train[:-168])\n"
        "    mase = mae / mae_naive\n"
        "    \n"
        "    metrics = {'MAE': mae, 'RMSE': rmse, 'sMAPE': smape, 'MASE': mase}\n"
        "    if y_lower is not None and y_upper is not None:\n"
        "        inside = (y_true >= y_lower) & (y_true <= y_upper)\n"
        "        metrics['Coverage'] = 100 * np.mean(inside)\n"
        "    return metrics\n\n"
        "feb_df = df['2025-02-01 00:00:00':'2025-02-28 23:00:00']\n"
        "aug_df = df['2025-08-01 00:00:00':'2025-08-31 23:00:00']\n\n"
        "results = {}\n"
        "for window_name, test_df in [(\"February 2025\", feb_df), (\"August 2025\", aug_df)]:\n"
        "    print(f\"\\nEvaluating {window_name}...\")\n"
        "    act, p_dir, p_lower, p_upper = evaluate_rolling_xgboost(test_df, df_h_dict)\n"
        "    results[window_name] = (act, p_dir, p_lower, p_upper)\n"
        "    # train_df target variable used for naive calculation baseline\n"
        "    train_df = df[:test_df.index[0] - pd.Timedelta(hours=1)]\n"
        "    metrics = calculate_metrics(act.flatten(), p_dir.flatten(), train_df['energy'], p_lower.flatten(), p_upper.flatten())\n"
        "    print(f\"\\nResults for {window_name} (XGBoost Rolling Retraining):\")\n"
        "    print(metrics)"
    ))
    
    # Cell 8: Plotting sample day
    cells.append(nbf.v4.new_code_cell(
        "sample_origin = '2025-08-15 00:00:00'\n"
        "origin_ts = pd.Timestamp(sample_origin)\n"
        "origins = aug_df[aug_df.index.hour == 0].index\n"
        "sample_idx = list(origins).index(origin_ts)\n\n"
        "act_sample = results['August 2025'][0][sample_idx]\n"
        "wea_preds = results['August 2025'][1][sample_idx]\n"
        "wea_lowers = results['August 2025'][2][sample_idx]\n"
        "wea_uppers = results['August 2025'][3][sample_idx]\n\n"
        "plt.figure(figsize=(12, 6))\n"
        "plt.plot(range(1, 25), act_sample, label='Actual', marker='o', color='black')\n"
        "plt.plot(range(1, 25), wea_preds, label='XGBoost Point Prediction', linestyle='--', color='red')\n"
        "plt.fill_between(range(1, 25), wea_lowers, wea_uppers, color='red', alpha=0.15, label='XGBoost 90% Prediction Interval')\n"
        "plt.title(f\"Probabilistic XGBoost Forecast with Rolling Train - Origin: {sample_origin}\")\n"
        "plt.xlabel('Horizon (Hours)')\n"
        "plt.ylabel('Energy Demand (MW)')\n"
        "plt.legend()\n"
        "plt.grid(True)\n"
        "plt.show()"
    ))
    
    nb['cells'] = cells
    
    os.makedirs('notebooks/xgboost-rolling', exist_ok=True)
    with open('notebooks/xgboost-rolling/ieso-xgboost-rolling.ipynb', 'w') as f:
        nbf.write(nb, f)
    print("Created notebooks/xgboost-rolling/ieso-xgboost-rolling.ipynb")

if __name__ == '__main__':
    create_ercot_notebook()
    create_ieso_notebook()
